Refactor: check_git_configs signal an error only if user.name not set

diff --git a/gh-soc b/gh-soc
--- a/gh-soc
+++ b/gh-soc
@@ -77,26 +77,18 @@ check_git_configs() {
 
   local git_user_name=$(git config --global user.name)
   local git_user_email=$(git config --global user.email)
-  # Initialize a flag to track if any config is not set
-  local git_configs_noexists_flag=0
 
   # Check if the user has set up the git user name and email
-  if [[ -z "${git_user_name}" ]]; then
-    echo -n "${ERR} Git user name is not set. Please run: " >&2
-    echo "'git config --global user.name \"Your Name\"'." >&2
-    git_configs_noexists_flag=1
-  fi
-
   if [[ -z "${git_user_email}" ]]; then
-    echo -n "${ERR} Git user email is not set. Please run: " >&2
-    echo "'git config --global \"your_email@example.com\"'." >&2
-    git_configs_noexists_flag=1
+    echo -n "${WRN} Git user email is not set. You can set it up with: "
+    echo "'git config --global \"your_email@example.com\"'."
   fi
 
-  if [[ "${git_configs_noexists_flag}" -eq 1 ]]; then
-    echo -n "${ERR} For proper functioning of '${FUNCNAME[1]}' command, " >&2
-    echo -n "it is required that the git user name and email are set up " >&2
-    echo "on the local machine." >&2
+  if [[ -z "${git_user_name}" ]]; then
+    echo -n "${ERR} Git user name is not set. For proper functioning of " >&2
+    echo -n "'${FUNCNAME[1]}' command, it is required that the git user " >&2
+    echo -n "name is set up on the local machine. Please run:" >&2
+    echo "'git config --global user.name \"Your Name\"'." >&2
     exit 1
   fi
 }
