Add delete_repositories function

diff --git a/gh-soc b/gh-soc
--- a/gh-soc
+++ b/gh-soc
@@ -202,6 +202,25 @@ fork_repositories() {
   echo "${OK} Forking repositories has been completed"
 }
 
+# Delete repositories listed in TARGET_REPOS array in user_config.sh file from
+# GH_ORG_NAME. Usage: delete_repositories
+delete_repositories() {
+
+  for ((i=0; i<"${#TARGET_REPOS[@]}"; i++)); do
+
+    # deleting a repo
+    gh repo delete "$GH_ORG_NAME"/"${TARGET_REPOS[i]}" --yes
+
+    if [[ $? -ne 0 ]]; then
+      echo -n "${ERR} An error occurred while deleting the repository" >&2
+      echo "$GH_ORG_NAME"/"${TARGET_REPOS[i]}" >&2
+      exit 1
+    fi
+  done
+
+  echo "${OK} Deletion of the repositories has been completed."
+}
+
 # Sets specified repositories in GH_ORG_NAME as private and marks them as
 # templates.
 # Usage: set_repo_as_private_template
