Correct the error with exit status checking of getting team member list into array

diff --git a/gh-soc b/gh-soc
--- a/gh-soc
+++ b/gh-soc
@@ -1372,16 +1372,22 @@ get_team_members_list() {
 
   # Declare a local variable for the return value
   local -a team_members
+  local response
+  local status
 
-  readarray -t team_members < <(gh api \
-                    --header "Accept: ${GH_API_ACCEPT_HEADER}" \
-                    --header "X-GitHub-Api-Version: ${GH_API_VERSION_HEADER}" \
-                    --method GET \
-                    /orgs/"${GH_ORG_NAME}"/teams/"${GH_TEAM_NAME}"/members \
-                    --paginate \
-                    --jq '.[].login')
+  # Execute gh api and capture its response and exit status
+  response=$(gh api \
+                --header "Accept: ${GH_API_ACCEPT_HEADER}" \
+                --header "X-GitHub-Api-Version: ${GH_API_VERSION_HEADER}" \
+                --method GET \
+                /orgs/"${GH_ORG_NAME}"/teams/"${GH_TEAM_NAME}"/members \
+                --paginate \
+                --jq '.[].login') && status=$? || status=$?
 
-  if [[ $? -eq 0 ]]; then
+  # Read the output into the team_members array
+  readarray -t team_members <<< "${response}"
+
+  if [[ $status -eq 0 ]]; then
     echo "${team_members[@]}"
   else
     echo -n "${ERR} An error occurred while obtaining the members list of "
