Add valide_user_names function and refactor functions for url compatibility validation

diff --git a/gh-soc b/gh-soc
--- a/gh-soc
+++ b/gh-soc
@@ -1163,11 +1163,6 @@ create_repo_from_template() {
   echo "${OK} Creating repos from templates has been completed"
 }
 
-
-# TODO:
-# For tests
-# END:
-
 assign_repo_to_team() {
   # Disable the script's abort-on-first-error feature.
   set +o errexit
@@ -1197,8 +1192,7 @@ assign_repo_to_team() {
 delete_team() {
   # Disable the script's abort-on-first-error feature.
   set +o errexit
-  echo "Deleting the '${GH_TEAM_NAME}' team from the '${GH_ORG_NAME}' organization"
-  exit
+
   gh api \
      --method DELETE \
      --header "Accept: ${GH_API_ACCEPT_HEADER}" \
@@ -1327,26 +1321,44 @@ validate_non_empty_string() {
   if [[ -z "${var_value}" ]]; then
     echo "${ERR} '${var_name}' is empty." >&2
   else
-    echo "${YUP} '${var_name}' is non-empty: ${var_value}."
+    echo "${YUP} '${var_name}' is non-empty: '${var_value}'."
   fi
 }
 
-validate_url_compatibility() {
+validate_owner_name() {
   if [[ "$#" -lt 2 ]]; then
     echo -n "${ERR} Insufficient arguments provided for the " >&2
-    echo "'validate_url_compatibility' function." >&2
+    echo "'validate_owner_name' function." >&2
     exit 1
   fi
 
   local var_name="$1"
   local var_value="$2"
 
-  if [[ "${var_value}" =~ ^[a-zA-Z0-9_-]+$ ]]; then
-    echo "${YUP} '${var_name}' has valid URL value: ${var_value}."
+  if [[ "${var_value}" =~ ^[a-zA-Z0-9]+(-[a-zA-Z0-9]+)*$ ]]; then
+    echo "${YUP} '${var_name}' has valid value: '${var_value}'."
   else
-    echo "${ERR} '${var_name}' has invalid URL value: ${var_value}." >&2
+    echo "${ERR} '${var_name}' has invalid value: '${var_value}'." >&2
   fi
 }
+
+validate_team_name() {
+  if [[ "$#" -lt 2 ]]; then
+    echo -n "${ERR} Insufficient arguments provided for the " >&2
+    echo "'validate_team_name' function." >&2
+    exit 1
+  fi
+
+  local var_name="$1"
+  local var_value="$2"
+
+  if [[ "${var_value}" =~ ^[a-zA-Z0-9]+([_-][a-zA-Z0-9]+)*$ ]]; then
+    echo "${YUP} '${var_name}' has valid value: '${var_value}'."
+  else
+    echo "${ERR} '${var_name}' has invalid value: '${var_value}'." >&2
+  fi
+}
+
 
 # Function to validate numeric values
 validate_numeric() {
@@ -1360,9 +1372,9 @@ validate_numeric() {
   local var_value="$2"
 
   if ! [[ "${var_value}" =~ ^[0-9]+$ ]]; then
-    echo "${ERR} '${var_name}' has not numeric value: ${var_value}." >&2
+    echo "${ERR} '${var_name}' has not numeric value: '${var_value}'." >&2
   else
-    echo "${YUP} '${var_name}' has numeric value: ${var_value}."
+    echo "${YUP} '${var_name}' has numeric value: '${var_value}'."
   fi
 }
 
@@ -1386,7 +1398,7 @@ validate_non_empty_array() {
 }
 
 # Function to validate no empty elements in arrays
-validate_no_empty_elements() {
+validate_no_empty_array_elements() {
   if [[ "$#" -lt 2 ]]; then
     echo -n "${ERR} Insufficient arguments provided for the " >&2
     echo "'validate_no_empty_elements' function." >&2
@@ -1406,11 +1418,11 @@ validate_no_empty_elements() {
   echo "${YUP} '${var_name}' has no empty elements."
 }
 
-# Function to validate URL compatibility for each element in an array
-validate_array_elements_url_compatibility() {
+# Function to validate repo names for each element in an array
+validate_repo_names() {
   if [[ "$#" -lt 2 ]]; then
     echo -n "${ERR} Insufficient arguments provided for the " >&2
-    echo "'validate_array_elements_url_compatibility' function." >&2
+    echo "'validate_repo_names' function." >&2
     exit 1
   fi
 
@@ -1419,12 +1431,45 @@ validate_array_elements_url_compatibility() {
   local -a arr=("$@")
 
   for element in "${arr[@]}"; do
-    if ! [[ "${element}" =~ ^[a-zA-Z0-9_-]+$ ]]; then
-      echo "${ERR} '${var_name}' contains a non-compatible URL element: ${element}." >&2
+    if ! [[ "${element}" =~ ^[a-zA-Z0-9_.-]+$ ]]; then
+      echo -n "${ERR} '${var_name}' contains a non-valid element: " >&2
+      echo -n "'${element}'. Repository names can only contain alphanumeric " >&2
+      echo -n "characters, dot ('.'),  hyphen-minus character ('-'), " >&2
+      echo "and the underscore ('_')." >&2
       return
     fi
   done
-  echo "${YUP}  All elements in '${var_name}' are compatible with URL."
+  echo "${YUP}  All elements in '${var_name}' are valid."
+}
+
+validate_user_names() {
+  # The array of user names can be empty, so we need to check if at least one
+  # element is provided.
+  if [[ "$#" -lt 1 ]]; then
+    echo -n "${ERR} Insufficient arguments provided for the " >&2
+    echo "'validate_user_names' function." >&2
+    exit 1
+  fi
+
+  local var_name="$1"
+  shift # Remove the first argument to treat the rest as an array
+  local -a arr=("$@")
+
+  # Proceed only if the array is not empty
+  if [[ "${#arr[@]}" -eq 0 ]]; then
+    echo "${YUP}  The array '${var_name}' is empty. No validation needed."
+    return
+  fi
+
+  for element in "${arr[@]}"; do
+    if ! [[ "${element}" =~ ^[a-zA-Z0-9-]+$ ]]; then
+      echo -n "${ERR} '${var_name}' contains a non-valid element: " >&2
+      echo -n "'${element}'. User names can be empty or contain alphanumeric" >&2
+      echo " characters and hyphen-minus character ('-')." >&2
+      return
+    fi
+  done
+  echo "${YUP}  All elements in '${var_name}' are valid."
 }
 
 # Function to check for duplicate elements in an array
@@ -1449,7 +1494,7 @@ validate_no_duplicates() {
 
   for element in "${arr[@]}"; do
     if [[ -n "${arr_map[${element}]}" ]]; then
-      echo "${ERR} '${var_name}' has duplicate elements: ${element}." >&2
+      echo "${ERR} '${var_name}' has duplicate elements: '${element}'." >&2
       return
     fi
     arr_map["${element}"]=1
@@ -1857,13 +1902,10 @@ precheck() {
 
   echo "Validation of global variables from the 'user_config.sh' file:"
   # Variables validations
-  validate_url_compatibility "GH_ORG_NAME" "${GH_ORG_NAME}"
-  validate_url_compatibility "GH_TEAM_NAME" "${GH_TEAM_NAME}"
-
-  # TODO:
-  # This variable can be empty, but the names must be consistent with the URL
-  # validate_url_compatibility "GH_TEAM_MEMBERS_EXCLUDED_FROM_REVIEWING"
-  # END:
+  validate_owner_name "GH_ORG_NAME" "${GH_ORG_NAME}"
+  validate_team_name "GH_TEAM_NAME" "${GH_TEAM_NAME}"
+  validate_user_names "GH_TEAM_MEMBERS_EXCLUDED_FROM_REVIEWING" \
+		      "${GH_TEAM_MEMBERS_EXCLUDED_FROM_REVIEWING[@]}"
 
   validate_non_empty_string "TARGET_PROJECT_TITLE" "${TARGET_PROJECT_TITLE}"
 
@@ -1871,25 +1913,23 @@ precheck() {
   echo
   validate_non_empty_array "TARGET_REPOS" "${TARGET_REPOS[@]}"
   echo
-  validate_no_empty_elements "TARGET_REPOS" "${TARGET_REPOS[@]}"
-  validate_array_elements_url_compatibility "TARGET_REPOS" "${TARGET_REPOS[@]}"
+  validate_repo_names "TARGET_REPOS" "${TARGET_REPOS[@]}"
   validate_no_duplicates "TARGET_REPOS" "${TARGET_REPOS[@]}"
 
   echo "Validation of global variables from the 'source_config.sh' file:"
   # Variable validations
-  validate_url_compatibility "SOURCE_REPOS_OWNER" "${SOURCE_REPOS_OWNER}"
-  validate_url_compatibility "SOURCE_PROJECT_OWNER" "${SOURCE_PROJECT_OWNER}"
+  validate_owner_name "SOURCE_REPOS_OWNER" "${SOURCE_REPOS_OWNER}"
+  validate_owner_name "SOURCE_PROJECT_OWNER" "${SOURCE_PROJECT_OWNER}"
   validate_numeric "SOURCE_PROJECT_NUMBER" "${SOURCE_PROJECT_NUMBER}"
 
   # Arrays validations
   echo
   validate_non_empty_array "SOURCE_REPOS" "${SOURCE_REPOS[@]}"
   echo
-  validate_no_empty_elements "SOURCE_REPOS" "${SOURCE_REPOS[@]}"
-  validate_array_elements_url_compatibility "SOURCE_REPOS" "${SOURCE_REPOS[@]}"
+  validate_repo_names "SOURCE_REPOS" "${SOURCE_REPOS[@]}"
   validate_no_duplicates "SOURCE_REPOS" "${SOURCE_REPOS[@]}"
   validate_non_empty_array "SOURCE_FILES" "${SOURCE_FILES[@]}"
-  validate_no_empty_elements "SOURCE_FILES" "${SOURCE_FILES[@]}"
+  validate_no_empty_array_elements "SOURCE_FILES" "${SOURCE_FILES[@]}"
   validate_no_duplicates "SOURCE_FILES" "${SOURCE_FILES[@]}"
 }
 
@@ -1922,14 +1962,15 @@ fi
 if [[ ! -f "${user_config_path}" ]]; then
 cat << 'EOF' > "${user_config_path}"
 # ORGANIZATION CONFIGS----------------------------------------------------------#
+# The organization name may only contain alphanumeric characters or single
+# hyphens, and cannot begin or end with a hyphen ('-').
 readonly GH_ORG_NAME='' # insert here your GitHub organization name
 
 # TEAM CONFIGS------------------------------------------------------------------#
-# Insert your GitHub team name and others between quotes. The name may contain
-# only the ASCII letters 'a' through 'z' (in a case-insensitive manner), the
-# digits 0 through 9, the hyphen-minus character ('-'), and the underscore
-# ('_').
+# The team name name may contain only alphanumeric characters, a hyphen-minus
+# character ('-'), and an underscore ('_').
 readonly GH_TEAM_NAME='SoC-DS'
+
 readonly GH_TEAM_DESCRIPTION='SoC Data Science Course'
 readonly GH_TEAM_MEMBERS_EXCLUDED_FROM_REVIEWING=()
 
@@ -1939,9 +1980,8 @@ readonly TARGET_REPO_DESCRIPTION='SoC Data Science Course'
 # New repository names: rename according to your preferences, but choose names
 # that are not part of others. The first repository name may be an exception, as
 # in our example: the repository name 'soc-datascience' is part of others. Names
-# may contain only the ASCII letters 'a' through 'z' (in a case-insensitive
-# manner), the digits 0 through 9, the dot ('.'), the hyphen-minus character
-# ('-'), and the underscore ('_').
+# may contain only alphanumeric characters, a hyphen-minus
+# character ('-'), an underscore ('_') and a dot ('.').
 TARGET_REPOS=(
   'soc-datascience'
   'soc-datascience-hello'
