Add create_private_repos_from_templates function implementation
Add create_private_repos_from_templates evaluation to the sync command
Remove fork_repositories and set_repo_as_private_template evaluations from the
sync command

diff --git a/gh-soc b/gh-soc
--- a/gh-soc
+++ b/gh-soc
@@ -208,6 +208,27 @@ fork_repositories() {
   echo "${OK} Forking repositories has been completed"
 }
 
+# Create repositories in GH_ORG_NAME from SOURCE_REPOS_OWNER templates. Usage:
+# create_private_repos_from_templates
+create_private_repos_from_templates() {
+
+  for ((i=0; i<"${#SOURCE_REPOS[@]}"; i++)); do
+
+    # Create a repository in an organization from a template.
+    gh repo create "${GH_ORG_NAME}"/"${TARGET_REPOS[i]}" \
+       --template "${SOURCE_REPOS_OWNER}"/"${SOURCE_REPOS[i]}" \
+       --private=true
+
+    if [[ $? -ne 0 ]]; then
+      echo -n "${ERR} An error occurred while creating the " >&2
+      echo -n "${GH_ORG_NAME}/${TARGET_REPOS[i]} repository from " >&2
+      echo "the ${SOURCE_REPOS_OWNER}/${SOURCE_REPOS[i]} template" >&2
+      exit 1
+    fi
+  done
+  echo "${OK} Creating repositories has been completed"
+}
+
 # Delete repositories listed in TARGET_REPOS array in user_config.sh file from
 # GH_ORG_NAME. Usage: delete_repositories
 delete_repositories() {
@@ -2224,13 +2245,11 @@ sync() {
     # Disable the script's abort-on-first-error feature.
     set +o errexit
 
-    # Fork the main repository and all materials linked in the 'Repository
-    # for lab & home activities' column in the README.md and defined in the
-    # 'SOURCE_REPOS' array in the 'source_config.sh' file.
-    echo 'Running fork_repositories()'
-    fork_repositories
-    echo 'Running set_repo_as_private_template()'
-    set_repo_as_private_template
+    # Create repositories defined in the 'TARGET_REPOS' array in the
+    # 'user_config.sh' from the 'SOURCE_REPOS' repository templates array in the
+    # 'source_config.sh' file.
+    echo 'Running create_private_repos_from_templates()'
+    create_private_repos_from_templates
     echo 'Running set_repos_descriptions()'
     set_repos_descriptions
     echo 'Running update_repo_without_cloning()'
