Add check_if_repos_are_templates function implementation.
Refacor: remove 'source' and 'target' prefixes from the local variable names in
check_if_repos_exist and check_if_repos_noexist functions. Remove 'flag' postfix
from the local variable in check_if_repos_exist and check_if_repos_noexist
functions.

diff --git a/gh-soc b/gh-soc
--- a/gh-soc
+++ b/gh-soc
@@ -98,10 +98,9 @@ check_git_configs() {
   fi
 }
 
-# Checks if a repositories listed in the array in the config file
-# exist. Aborts the script with an error message if any repository does not
-# exist. Usage: check_if_repos_exist <source_repos_owner>
-# <source_repos_name> <source_repos>
+# Checks if repositories listed in the array in the config file exist. Aborts
+# the script with an error message if any repository does not exist. Usage:
+# check_if_repos_exist <repos_owner> <repos_name> <repos>
 check_if_repos_exist() {
 
   if [[ "$#" -lt 2 ]]; then
@@ -110,78 +109,115 @@ check_if_repos_exist() {
     exit 1
   fi
 
-  local source_repos_owner="$1"
+  local repos_owner="$1"
   shift # Remove the argument
-  local source_repos_name="$1"
+  local repos_name="$1"
   shift # Remove the argument to treat the rest as an array
-  local -a source_repos=("$@")
+  local -a repos=("$@")
 
   # Initialize a flag to track if any repository does not exist
-  local repo_noexists_flag=0
+  local repo_noexists=0
 
-  for ((i=0; i<"${#source_repos[@]}"; i++)); do
+  for ((i=0; i<"${#repos[@]}"; i++)); do
     # Check if the repository exists
-    if gh repo view "${source_repos_owner}/${source_repos[i]}" &> /dev/null; then
-      echo -n "${YUP} Repository ${source_repos_owner}/${source_repos[i]} "
+    if gh repo view "${repos_owner}/${repos[i]}" &> /dev/null; then
+      echo -n "${YUP} Repository ${repos_owner}/${repos[i]} "
       echo "exists as expected."
     else
-      echo -n "${ERR} Repository ${source_repos_owner}/${source_repos[i]} " >&2
-      echo "no exists." >&2
-      repo_noexists_flag=1
+      echo "${ERR} Repository ${repos_owner}/${repos[i]} no exists." >&2
+      repo_noexists=1
     fi
   done
 
   # Check the flag and exit with an error if any repository does not exist
-  if [[ "${repo_noexists_flag}" -eq 1 ]]; then
+  if [[ "${repo_noexists}" -eq 1 ]]; then
     echo -n "${ERR} For proper functioning of '${FUNCNAME[1]}' command, " >&2
     echo -n "it is required that the repositories listed in the " >&2
-    echo -n "'${source_repos_name}' array in the config file exist " >&2
-    echo "on the '${source_repos_owner}' account." >&2
+    echo -n "'${repos_name}' array in the config file exist " >&2
+    echo "on the '${repos_owner}' GitHub account." >&2
     exit 1
   else
-    echo -n "${OK} The check to see if the '${source_repos_name}' "
+    echo -n "${OK} The check to see if the '${repos_name}' "
     echo "repositories exist has been completed."
   fi
 }
 
-# Checks if a repositories listed in the array in the config file do not already
+# Checks if repositories listed in the array in the config file do not already
 # exist. Aborts the script with an warning message if any repository already
-# exists. Usage: check_if_repos_noexist <target_repos_owner> <target_repos_name>
-# <target_repos>
+# exists. Usage: check_if_repos_noexist <repos_owner> <repos_name> <repos>
 check_if_repos_noexist() {
 
-  local target_repos_owner="$1"
+  local repos_owner="$1"
   shift # Remove the argument
-  local target_repos_name="$1"
+  local repos_name="$1"
   shift # Remove the argument to treat the rest as an array
-  local -a target_repos=("$@")
+  local -a repos=("$@")
 
   # Initialize a flag to track if any repository already exists
-  local repo_exists_flag=0
+  local repo_exists=0
 
-  for ((i=0; i<"${#target_repos[@]}"; i++)); do
+  for ((i=0; i<"${#repos[@]}"; i++)); do
     # Check if the repository exists
-    if ! gh repo view "${target_repos_owner}/${target_repos[i]}" &> /dev/null; then
-      echo -n "${YUP} Repository ${target_repos_owner}/${target_repos[i]} "
+    if ! gh repo view "${repos_owner}/${repos[i]}" &> /dev/null; then
+      echo -n "${YUP} Repository ${repos_owner}/${repos[i]} "
       echo "not yet exists as expected."
     else
-      echo -n "${WRN} Repository ${GH_ORG_NAME}/${TARGET_REPOS[i]} "
-      echo "already exists."
-      repo_exists_flag=1
+      echo "${WRN} Repository ${repos_owner}/${repos[i]} already exists."
+      repo_exists=1
     fi
   done
 
   # Check the flag and exit with a warning if any repository already exists. The
   # presence of repositories may be due to synchronizing repositories beforehand
   # or already having own repositories with the same names as the source ones.
-  if [[ "${repo_exists_flag}" -eq 1 ]]; then
-    echo -n "${WRN} The repositories listed in the '${target_repos_name}' "
-    echo -n "array in the config file already exist on the "
-    echo "'${target_repos_owner}' account."
+  if [[ "${repo_exists}" -eq 1 ]]; then
+    echo -n "${WRN} One or more repositories listed in the '${repos_name}'"
+    echo -n " array in the config file already exist on the "
+    echo "'${repos_owner}' GitHub account."
     exit 1
   else
-    echo -n "${OK} The check to see if the '${target_repos_name}' "
+    echo -n "${OK} The check to see if the '${repos_name}' "
     echo "repositories exist has been completed."
+  fi
+}
+
+# Checks if repositories in source repo owner GitHub account and listed in the
+# array in the config file are templates. Aborts the script with an error
+# message if any repository is not a template. Usage:
+# check_if_repos_are_templates <repos_owner> <repos_name> <repos>
+check_if_repos_are_templates() {
+
+    local repos_owner="$1"
+    shift # Remove the argument
+    local repos_name="$1"
+    shift # Remove the argument to treat the rest as an array
+    local -a repos=("$@")
+
+  # Initialize a flag to track if any repository is not a template
+  local repo_is_not_template=0
+
+  for ((i=0; i<"${#repos[@]}"; i++)); do
+    # Check if the repository is a template
+    if [[ $(gh api repos/"${repos_owner}/${repos[i]}" --jq '.is_template') == true ]]; then
+      echo -n "${YUP} Repository ${repos_owner}/${repos[i]} "
+      echo "is a template as expected."
+    else
+      echo -n "${WRN} Repository ${repos_owner}/${repos[i]} "
+      echo "is not a template."
+      repo_is_not_template=1
+    fi
+  done
+
+  # Check the flag and exit with a error if any repository is not a template.
+  if [[ "${repo_is_not_template}" -eq 1 ]]; then
+    echo -n "${ERR} For proper functioning of '${FUNCNAME[1]}' command, " >&2
+    echo -n "it is required that the repositories in '${repos_owner}' " >&2
+    echo -n "GitHub account and listed in the '${repos_name}' array " >&2
+    echo "in the config file are templates." >&2
+    exit 1
+  else
+    echo -n "${OK} The check to see if the '${repos_name}' repositories "
+    echo "are templates has been completed."
   fi
 }
 
